/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as KatalogRouteImport } from './routes/katalog'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MobilCarIdRouteImport } from './routes/mobil.$carId'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminMobilRouteImport } from './routes/_admin/admin.mobil'
import { Route as AdminAdminMobilBaruRouteImport } from './routes/_admin/admin.mobil.baru'
import { Route as AdminAdminMobilCarIdRouteImport } from './routes/_admin/admin.mobil.$carId'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogRoute = KatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilCarIdRoute = MobilCarIdRouteImport.update({
  id: '/mobil/$carId',
  path: '/mobil/$carId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminMobilRoute = AdminAdminMobilRouteImport.update({
  id: '/admin/mobil',
  path: '/admin/mobil',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminMobilBaruRoute = AdminAdminMobilBaruRouteImport.update({
  id: '/baru',
  path: '/baru',
  getParentRoute: () => AdminAdminMobilRoute,
} as any)
const AdminAdminMobilCarIdRoute = AdminAdminMobilCarIdRouteImport.update({
  id: '/$carId',
  path: '/$carId',
  getParentRoute: () => AdminAdminMobilRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/katalog': typeof KatalogRoute
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/tentang': typeof TentangRoute
  '/mobil/$carId': typeof MobilCarIdRoute
  '/admin/mobil': typeof AdminAdminMobilRouteWithChildren
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/mobil/$carId': typeof AdminAdminMobilCarIdRoute
  '/admin/mobil/baru': typeof AdminAdminMobilBaruRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/katalog': typeof KatalogRoute
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/tentang': typeof TentangRoute
  '/mobil/$carId': typeof MobilCarIdRoute
  '/admin/mobil': typeof AdminAdminMobilRouteWithChildren
  '/admin': typeof AdminAdminIndexRoute
  '/admin/mobil/$carId': typeof AdminAdminMobilCarIdRoute
  '/admin/mobil/baru': typeof AdminAdminMobilBaruRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/katalog': typeof KatalogRoute
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/tentang': typeof TentangRoute
  '/mobil/$carId': typeof MobilCarIdRoute
  '/_admin/admin/mobil': typeof AdminAdminMobilRouteWithChildren
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/mobil/$carId': typeof AdminAdminMobilCarIdRoute
  '/_admin/admin/mobil/baru': typeof AdminAdminMobilBaruRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/katalog'
    | '/kontak'
    | '/login'
    | '/tentang'
    | '/mobil/$carId'
    | '/admin/mobil'
    | '/admin/'
    | '/admin/mobil/$carId'
    | '/admin/mobil/baru'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/katalog'
    | '/kontak'
    | '/login'
    | '/tentang'
    | '/mobil/$carId'
    | '/admin/mobil'
    | '/admin'
    | '/admin/mobil/$carId'
    | '/admin/mobil/baru'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/katalog'
    | '/kontak'
    | '/login'
    | '/tentang'
    | '/mobil/$carId'
    | '/_admin/admin/mobil'
    | '/_admin/admin/'
    | '/_admin/admin/mobil/$carId'
    | '/_admin/admin/mobil/baru'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  KatalogRoute: typeof KatalogRoute
  KontakRoute: typeof KontakRoute
  LoginRoute: typeof LoginRoute
  TentangRoute: typeof TentangRoute
  MobilCarIdRoute: typeof MobilCarIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog': {
      id: '/katalog'
      path: '/katalog'
      fullPath: '/katalog'
      preLoaderRoute: typeof KatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobil/$carId': {
      id: '/mobil/$carId'
      path: '/mobil/$carId'
      fullPath: '/mobil/$carId'
      preLoaderRoute: typeof MobilCarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/mobil': {
      id: '/_admin/admin/mobil'
      path: '/admin/mobil'
      fullPath: '/admin/mobil'
      preLoaderRoute: typeof AdminAdminMobilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/mobil/baru': {
      id: '/_admin/admin/mobil/baru'
      path: '/baru'
      fullPath: '/admin/mobil/baru'
      preLoaderRoute: typeof AdminAdminMobilBaruRouteImport
      parentRoute: typeof AdminAdminMobilRoute
    }
    '/_admin/admin/mobil/$carId': {
      id: '/_admin/admin/mobil/$carId'
      path: '/$carId'
      fullPath: '/admin/mobil/$carId'
      preLoaderRoute: typeof AdminAdminMobilCarIdRouteImport
      parentRoute: typeof AdminAdminMobilRoute
    }
  }
}

interface AdminAdminMobilRouteChildren {
  AdminAdminMobilCarIdRoute: typeof AdminAdminMobilCarIdRoute
  AdminAdminMobilBaruRoute: typeof AdminAdminMobilBaruRoute
}

const AdminAdminMobilRouteChildren: AdminAdminMobilRouteChildren = {
  AdminAdminMobilCarIdRoute: AdminAdminMobilCarIdRoute,
  AdminAdminMobilBaruRoute: AdminAdminMobilBaruRoute,
}

const AdminAdminMobilRouteWithChildren = AdminAdminMobilRoute._addFileChildren(
  AdminAdminMobilRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminMobilRoute: typeof AdminAdminMobilRouteWithChildren
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminMobilRoute: AdminAdminMobilRouteWithChildren,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  KatalogRoute: KatalogRoute,
  KontakRoute: KontakRoute,
  LoginRoute: LoginRoute,
  TentangRoute: TentangRoute,
  MobilCarIdRoute: MobilCarIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
